import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { TopMenu } from  "./components";




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body className="min-h-screen">
      <TopMenu />
      { children }
    </body>
    </html>
  );
}

/*

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>{children}</body>
    </html>
  );
}
*/